# Generated by Django 3.0.5 on 2020-04-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ImageUrl',
            field=models.URLField(default='https://wallpaperstock.net/alien-vs-predator%2c-aliens%2c-console%2c-games-wallpapers_57764_1366x768.jpg'),
        ),
    ]
